export const STATIC_MODELS = [
  { id: 'gpt-5.4', owned_by: 'openai' },
  { id: 'gpt-5.4-mini', owned_by: 'openai' },
  { id: 'gpt-5.3-codex', owned_by: 'openai' },
  { id: 'claude-opus-4.6', owned_by: 'anthropic' },
  { id: 'claude-opus-4.8', owned_by: 'anthropic' },
  { id: 'claude-sonnet-4.6', owned_by: 'anthropic' },
  { id: 'moonshotai/kimi-k2.6', owned_by: 'moonshot' },
  { id: 'deepseek-ai/deepseek-v4-pro', owned_by: 'deepseek' },
  { id: 'qwen/qwen3.5-397b-a17b', owned_by: 'qwen' },
  { id: 'minimaxai/minimax-m2.7', owned_by: 'minimax' },
  { id: 'z-ai/glm-5.1', owned_by: 'z-ai' },
  { id: 'deepseek-v4-flash', owned_by: 'deepseek' },
  { id: 'glm-5.1', owned_by: 'zhipu' },
  { id: 'kimi-k2.6', owned_by: 'moonshot' },
  { id: 'minimax-m2.7', owned_by: 'minimax' },
  { id: 'qwen3.6-plus', owned_by: 'alibaba' },
  { id: 'qwen3.6-plus-thinking', owned_by: 'alibaba' },
  { id: 'qwen3.6-max-preview', owned_by: 'alibaba' },
  { id: 'gemini-3-flash-preview', owned_by: 'google' },
  { id: 'gemini-3.1-pro-preview', owned_by: 'google' },
];
